image: hashicorp/terraform-k8s

definitions:
  steps:
    - step: &terraform-test
        name: Testing terraform configuration
        image: hashicorp/terraform-k8s
        script:
            - cd ./terraform/dev/

            # hacky fix https://github.com/terraform-providers/terraform-provider-kubernetes/issues/679
            # !!!!
            #- export KUBERNETES_SERVICE_HOST=
            # !!!!

            - echo ${GCP_SECRET} > credentials.json
            - terraform init
            - terraform validate
            - terraform plan


    - step: &terraform-deploy
        name: Testing terraform configuration
        image: hashicorp/terraform-k8s
        script:
            - cd ./terraform/dev/
            - echo ${GCP_SECRET} > credentials.json
            
            
            
            - terraform init
            - terraform apply -input=false -auto-approve -no-color
              

pipelines:
    default:
      - step: *terraform-test

    branches:
        master:
            - step: *terraform-test
            - step: *terraform-deploy
              
            
