definitions:
  steps:
    - step: &terraform-test
        name: Testing terraform configuration
        image: kiwigrid/gcloud-kubectl-helm
        script:
            - cd ./terraform/dev/
            - echo ${GCP_SECRET} > credentials.json
            - gcloud auth activate-service-account --key-file=credentials.json
            - echo ${PROXY_SECRET} > proxyCreds.json

            # hacky fix https://github.com/terraform-providers/terraform-provider-kubernetes/issues/679
            # !!!!
            - export KUBERNETES_SERVICE_HOST=
            # !!!!

            - cd /tmp/
            - wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
            - unzip terraform_0.12.24_linux_amd64.zip
            - export PATH="$PATH:/tmp"

            - cd ${BITBUCKET_CLONE_DIR}/terraform/scripts/
            - /bin/bash tf-init.sh

    - step: &terraform-deploy
        name: Deploying terraform configuration
        image: kiwigrid/gcloud-kubectl-helm
        script:
            - cd ./terraform/dev/
            - echo ${GCP_SECRET} > credentials.json
            - gcloud auth activate-service-account --key-file=credentials.json
            - echo ${PROXY_SECRET} > proxyCreds.json

            # hacky fix https://github.com/terraform-providers/terraform-provider-kubernetes/issues/679
            # !!!!
            - export KUBERNETES_SERVICE_HOST=
            # !!!!

            - cd /tmp/
            - wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
            - unzip terraform_0.12.24_linux_amd64.zip
            - export PATH="$PATH:/tmp"

            - cd ${BITBUCKET_CLONE_DIR}/terraform/scripts/
            - /bin/bash tf-init.sh
            - /bin/bash tf-apply.sh

pipelines:
  branches:
    dev:
      - step: 
          <<: *terraform-deploy
          name: Deploy terraform configuration to Dev
          deployment: Dev
    master:
      - step: 
          <<: *terraform-test
          name: Testing terraform configuration for production

      - step:  
          <<: *terraform-deploy
          name: Deploy terraform configuration to Production
          deployment: Production
          trigger: manual
            
