image: hashicorp/terraform

definitions:
  steps:
    - step: &terraform-test
        name: Testing terraform configuration
        image: hashicorp/terraform
        script:
            - cd ./terraform/dev/

            # hacky fix https://github.com/terraform-providers/terraform-provider-kubernetes/issues/679
            # !!!!
            - export KUBERNETES_SERVICE_HOST=
            # !!!!

            - echo ${GCP_SECRET} > credentials.json
            - terraform init
            - terraform validate
            - terraform plan


    - step: &terraform-deploy
        name: Testing terraform configuration
        image: hashicorp/terraform
        script:
            - cd ./terraform/dev/
            - echo ${GCP_SECRET} > credentials.json
            
            
            - apt-get update && apt-get install -y apt-transport-https && apt-get install -y curl
            - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
            - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
            - apt-get update
            - apt-get install -y kubectl
            
            
            - terraform apply -input=false -auto-approve -no-color
              

pipelines:
    default:
      - step: *terraform-test

    branches:
        master:
            - step: *terraform-test
            - step: *terraform-deploy
              
            
