image: hashicorp/terraform:full

definitions:
  steps:
    - step: &terraform-test
        name: Testing terraform configuration
        image: hashicorp/terraform:full
        script:
            - cd ./terraform/dev/

            # hacky fix https://github.com/terraform-providers/terraform-provider-kubernetes/issues/679
            # !!!!
            - export KUBERNETES_SERVICE_HOST=
            # !!!!
            - echo ${GCP_SECRET} > credentials.json
            - terraform init
            - terraform validate
            - terraform plan

pipelines:
    default:
      - step: *terraform-test

    branches:
        master:
            - step: *terraform-test
            
