image: hashicorp/terraform:full

definitions:
  steps:
    - step: &terraform-test
        name: Testing terraform configuration
        image: hashicorp/terraform:full
        caches:
          - docker
        script:
            - echo ${GCP_SECRET} > credentials.json
            - cd ./terraform/dev/
            - terraform init
            - terraform validate
            - terraform plan



pipelines:
    default:
      - step: *terraform-test

    branches:
        master:
            - step: *terraform-test
