image: hashicorp/terraform

definitions:
  steps:
    - step: &terraform-test
        name: Testing terraform configuration
        image: hashicorp/terraform
        script:
            - cd ./terraform/dev/

            # hacky fix https://github.com/terraform-providers/terraform-provider-kubernetes/issues/679
            # !!!!
            - export KUBERNETES_SERVICE_HOST=
            # !!!!


            - sudo apt-get update && sudo apt-get install -y apt-transport-https
            - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
            - apt-get update
            - apt-get install -y kubectl

            - echo ${GCP_SECRET} > credentials.json
            - terraform init
            - terraform validate
            - terraform plan
            - terraform apply -input=false -auto-approve -no-color

pipelines:
    default:
      - step: *terraform-test

    branches:
        master:
            - step: *terraform-test
              
            
