image: google/cloud-sdk

definitions:
  steps:
    - step: &terraform-test
        name: Testing terraform configuration
        script:
            - cd ./terraform/dev/

            # hacky fix https://github.com/terraform-providers/terraform-provider-kubernetes/issues/679
            # !!!!
            - export KUBERNETES_SERVICE_HOST=
            # !!!!

            - wget https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip
            - unzip terraform_0.12.21_linux_amd64.zip

            - echo ${GCP_SECRET} > credentials.json
            - terraform init
            - terraform validate
            - terraform plan
            - terraform apply -input=false -auto-approve -no-color

pipelines:
    default:
      - step: *terraform-test

    branches:
        master:
            - step: *terraform-test
              
            
