apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-canary
spec:
  replicas: 10
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: rollout-canary
  template:
    metadata:
      labels:
        app: rollout-canary
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:red
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-canary-active
spec:
  selector:
    app: rollout-canary
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-canary-preview
spec:
  selector:
    app: rollout-canary
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rollout-canary-active-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: rollout-canary-active
spec:
  backend:
    serviceName: rollout-canary-active
    servicePort: 80


---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rollout-canary-preview-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: rollout-canary-preview
spec:
  backend:
    serviceName: rollout-canary-preview
    servicePort: 80



