apiVersion: argoproj.io/v1alpha1 #apps/v1 #
kind: Rollout #Deployment #
metadata:
  name: hello-world
spec:
  replicas: 6
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: gcr.io/bachelor-2020/hello-world:1.7
          name: hello-world
          ports:
            - containerPort: 8080
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
   ----- Everything above this comment are the same as a deployment -----
    blueGreen:
      autoPromotionEnabled: true
      activeService: hello-world
      previewService: hello-world-preview
      previewReplicaCount: 2
      scaleDownDelaySeconds: 60

---

apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: hello-world

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: hello-world-ip
spec:
  backend:
    serviceName: hello-world
    servicePort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: hello-world-preview
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: hello-world

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-preview-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: hello-world-ip
spec:
  backend:
    serviceName: hello-world-preview
    servicePort: 80



