apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-rest-deployment
  labels:
    app: test-rest
spec:
  replicas: 10
  revisionHistoryLimit: 5
  minReadySeconds: 30
  selector:
    matchLabels:
      app: test-rest
  template:
    metadata:
      labels:
        app: test-rest
    spec:
      containers:
        - name: test-rest
          image: gcr.io/bachelor-2020/test-rest:v1.19
          ports:
            - containerPort: 8080
          command: ["./main"]
          args: ["--config", "./config/.config.yml"]
          env:
            # These secrets are required to start the pod.
            # [START cloudsql_secrets]
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_NAME
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_NAME
            # [END cloudsql_secrets]
          volumeMounts:
            - name: test-rest-config-file
              mountPath: /go/config
              readOnly: true
      volumes:
        - name: test-rest-config-file
          secret:
            secretName: test-rest-config-file
---
apiVersion: v1
kind: Service
metadata:
  name: test-rest-service-external
spec:
  type: LoadBalancer
  selector:
    app: test-rest
  ports:
  - name: http
    port: 80
    targetPort: 8080





