apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-argocd
  namespace: argocd
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: test@test.com
    privateKeySecretRef:
      name: letsencrypt-argocd
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
