apiVersion: extensions/v1beta1
kind: Ingress
annotations:
    kubernetes.io/ingress.global-static-ip-name: 'app-static-ip-address'
metadata:
  name: traffic-router
spec:
  rules:
    - host: frontend.mydomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 80
