apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traffic-router
  annotations:
    kubernetes.io/ingress.global-static-ip-name: 'app-static-ip-address'
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: frontend-nodeport
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080