apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    kubernetes.io/ingress.global-static-ip-name: 'argo-static-ip-address'
spec:
  rules:
  - host: argo.fonn.es
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: https